# Generated by Django 5.0.6 on 2024-06-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.CharField(default='$ 0', max_length=12),
        ),
    ]
